geometry_msgs/Point target_position
int16 img_id
float32 approach_dist
bool hand_over
---
# Error codes
uint16 NONE = 0                     # Success
uint16 NAV_ERROR = 1                 # Navigation action error
uint16 BASE_POSE_UNAVAILABLE = 2   # Unable to get robot base pose from tf
uint16 IMAGE_ID_NOT_FOUND = 3     # Image ID not found in data.json

uint16 error_code
string error_msg
---
