string sentence
---
int32 error_code
int32 SUCCESSFUL = 0
int32 OBJECT_NOT_FOUND = -1
int32 JOINT_STATE_UNAVAILABLE = -2
int32 UNKNOWN_ERROR = -3

string error_string
---
std_msgs/Header header
int32 progress